### ISSUE TITLE
FIX REMOVE

### ISSUE THREAD

**Issue by Jackdouglas99** [jamiepine/pulse#16]
When trying to remove data from a group collection.remove(id, 'group') just does not work

**Comment by jamiepine** [comment]
Remove does work, (you were trying to remove from the wrong group, as we debugged)

However here's some things to note that came to my attention while debugging:

- removing from a dynamic group errors, something to do with the dependency graph
- `move()` does the same as `remove()` if you don't define a destination 
- `remove()` without a group specified should remove from all groups
- `delete()` exists and does exactly that
