### ISSUE TITLE
Vanilla Setup for React-Native project not working

### ISSUE THREAD

**Issue by timokoenig** [jamiepine/pulse#20]
When I tried to integrate pulse framework into an example react-native project I get an error that the storage is missing. This is misleading with the documentation from the README.md  `Local storage is the default and you don't need to define a storage object for it to work.`. 

## Expected Behavior
The pulse setup works without defining a new storage.

## Current Behavior
You have to define a simple storage object to make it work, otherwise you get the following error:

```
 this._global.storage.get is not a function. ‘(In this._global_storage.get(‘_’)’, ‘this._global.storage.get’ is undefined)

  initStorage - Collection.js:132:33 
```

## Extra Information
To fix the error you have to define a storage with those functions when creating the library. 

```
 pulse = new Pulse.Library({
  storage: {
    async: true,
    store: {},
    get: function(key) {
      return this.store[key];
    },
    set: function(key, value) {
      this.store[key] = value.toString();
    },
    clear: function() {
      this.store = {};
    },
    remove: function(key) {
      delete this.store[key];
    }
  },
  collections: {
    channels: {},
    posts: {}
  }
});
```

## Environment Information
react-native-cli: 2.0.1
react: 16.8.3
react-native: 0.59.8
pulse-framework: 1.9.4

## Steps to reproduce
- `react-native init AwesomeProject`
- `cd AwesomeProject`
- `npm install`
- `npm i pulse-framework --save` 
- Add vanilla pulse setup to App.js
- `react-native run-ios`

**Comment by jamiepine** [comment]
I apologies for my poor wording, localStorage is the default, but React Native does not have the typical browser localStorage, so you must bind a custom storage solution of your choice. I will improve this section of the documentation.

**Comment by timokoenig** [comment]
Got it. Thanks for the clarification
