### ISSUE TITLE
React for Production

### ISSUE THREAD

**Issue by TimothyCole** [jamiepine/pulse#24]
When building react for production you don't necessarily have [`_reactInternalInstance`](https://github.com/jamiepine/pulse/blob/4e4578bc966cc60d03bbdfc1af8fa468b64fbf87/lib/Collection.js#L1007) all the time. There is an alternative of using `config.framework = "react"` but that's not documented anywhere. Please document. :slightly_smiling_face: 

## Expected Behavior

To be documented...

## Current Behavior

Not documented at all.

**Comment by jamiepine** [comment]
https://twitter.com/jamiepine/status/1142777645526110208

**Comment by jamiepine** [comment]
I guess copy/paste isn't my thing: https://github.com/jamiepine/pulse#note-react-users
